name: CI/CD con Docker Compose y Docker Scout

on:
  push:
    branches:
      - main

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Docker (última versión con docker scout)
        uses: docker/setup-docker@v3
        with:
          version: '24.0.5'  # Cambia a la versión más reciente estable si quieres

      - name: Verificar versión de Docker y Docker Scout
        run: |
          docker --version
          docker scout --help

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: |
          docker build -t tu_usuario/tu_app:latest .

      - name: Push imagen a Docker Hub
        run: |
          docker push tu_usuario/tu_app:latest

      - name: Escanear imagen con Docker Scout
        run: |
          docker scout quickview tu_usuario/tu_app:latest

      - name: Cargar variables de entorno
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> .env
          echo "PORT=5000" >> .env

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Desplegar con Docker Compose
        run: |
          docker-compose --env-file .env up -d
