name: CI Docker Scout Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mjtaehyung/proyectofinal:latest .

      - name: Download Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan image with Docker Scout
        run: |
          docker scout cves vianeyarteaga/proyectofinal:latest > scout-report.md || echo "Scan failed"

      - name: Upload CVE Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-report
          path: scout-report.md
