name: Docker Scout CI Scan

on:
  push:
    branches:
      - main

jobs:
  scout-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t mjtaehyung/proyecto:latest .

      - name: Scan Docker image with Scout CLI
        id: scan
        run: |
          docker scout cves mjtaehyung/proyecto:latest --format markdown > scout-report.md
          # Buscar si hay vulnerabilidades críticas en el reporte y marcar output para condiciones posteriores
          if grep -q "CRITICAL" scout-report.md; then
            echo "has_critical_vulnerabilities=true" >> $GITHUB_OUTPUT
          else
            echo "has_critical_vulnerabilities=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Scout Report
        uses: actions/upload-artifact@v4
        with:
          name: scout-report
          path: scout-report.md

      - name: Fail if critical vulnerabilities found
        if: steps.scan.outputs.has_critical_vulnerabilities == 'true'
        run: exit 1
