name: CI Docker Scout Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scout-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:latest .

      - name: Install Docker Scout CLI
        run: |
          curl -Lo scout https://github.com/docker/scout-cli/releases/latest/download/scout_linux_amd64
          chmod +x scout
          sudo mv scout /usr/local/bin/scout
          scout version

      - name: Run Docker Scout CVE Scan
        run: |
          scout cves ${{ github.repository }}:latest > scout-report.md

      - name: Upload CVE Report
        uses: actions/upload-artifact@v4
        with:
          name: scout-report
          path: scout-report.md
