name: CI Docker Scout Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-scout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull mjtaehyung/proyecto:latest

      - name: List Docker images localmente
        run: docker images

      - name: Download Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan image with Docker Scout (direct output)
        run: docker scout cves mjtaehyung/proyecto:latest || echo "Scan failed"

      - name: Scan image with Docker Scout and save report
        run: docker scout cves mjtaehyung/proyecto:latest > reporte.md || echo "Scan failed"

      - name: Show CVE Report in console
        run: cat reporte.md || echo "No report content"

      - name: Upload CVE Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reporte-scout
          path: reporte.md
