name: Supervisión continua de seguridad con Docker Scout

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir imagen Docker
        run: docker build -t tu_usuario/nombre-del-proyecto:latest .

      - name: Subir imagen a Docker Hub
        run: docker push tu_usuario/nombre-del-proyecto:latest

      - name: Escanear imagen con Docker Scout
        run: |
          docker scout quickview tu_usuario/nombre-del-proyecto:latest
          docker scout cves tu_usuario/nombre-del-proyecto:latest
