name: CI Scout Scan on Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  scout-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t mi-imagen:latest .

      - name: Descargar e instalar Docker Scout CLI
        run: curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --

      - name: Escaneo con Docker Scout
        run: ./docker-scout cves mi-imagen:latest --format markdown --output reporte.md || true

      - name: Subir reporte como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: reporte-scout
          path: reporte.md
