name: Supervisión continua con Docker Scout

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Construir imagen Docker
        run: docker build -t mjtaehyung/proyecto:latest .

      - name: Subir imagen Docker a Docker Hub
        run: docker push mjtaehyung/proyecto:latest

      - name: Escanear imagen con Docker Scout
        run: |
          docker scout quickview mjtaehyung/proyecto:latest
          docker scout cves mjtaehyung/proyecto:latest
